### ISSUE TITLE
build not successful

### ISSUE THREAD

**Issue by eeeandeee** [ayosol/hngstrikework_app#22]
Dear Ayosol... Build not successful atm

**Comment by ElNuru247** [comment]
Hope you have internet connection... if you do,please pull the changes made on the repo to your machine and try again.

i hope it solves your problem,if it does,pls let us know so the Issue could be closed.

thanks :)

**Comment by eeeandeee** [comment]
Working please close

Ethan & Erikka

On Nov 9, 2018 8:39 PM, "Ismail Nurudeen" <notifications@github.com> wrote:

Hope you have internet connection... if you do,please pull the changes made
on the repo to your machine and try again.

i hope it solves your problem,if it does,pls let us know so the Issue could
be closed.

thanks :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ayosol/hngstrikework_app/issues/22#issuecomment-437472287>,
or mute the thread
